### ISSUE TITLE
Compabilty with upcoming Meteor 1.2

### ISSUE THREAD

**Issue by Markusxmr** [frozeman/meteor-build-client#11]
Greetings,
Probably to early for this one, but could you tell if your build tool will be compatible with Meteor 1.2 by default?

**Comment by lukeadams** [comment]
Have you tested it? (Clone a testing version of the Meteor repo and see what happens) Theoretically it should work. *crosses fingers*

**Comment by Markusxmr** [comment]
Did not thought of that, thank you. Will do. I'll check back with results

**Comment by Markusxmr** [comment]
@lukeadams tryed the Meteor Build Client with Meteor 1.2 rc12, and it worked "out of the box"

**Comment by Markusxmr** [comment]
@frozeman Thx again, for this tool

**Comment by frozeman** [comment]
Ok super, good to hear :) I didn't try yet.

**Comment by mstn** [comment]
I had to add standard-minifiers for a newly created 1.2 application. Otherwise the big css file was not created and the css file name was "undefined". When you update a pre-1.2 app, standard-minifiers is added by default. Hence, the problem should be only with fresh 1.2 apps. After adding the package it worked very well. Thanks.

**Comment by frozeman** [comment]
PR welcome :)

**Comment by frozeman** [comment]
@mstn could you try if you get the error again with the latest version 0.2.1?

**Comment by mstn** [comment]
I tried with 0.2.2, but I have the same problem.

**Comment by mstn** [comment]
I do not know if I have time to look into it before next week. To make it work I added standard-minifiers to the main application, not to the package.

**Comment by dr-dimitru** [comment]
This issue is archived.
Feel free to reopen it in case if the issue is still persists on your end.
