### ISSUE TITLE
Meteor is undefined

### ISSUE THREAD

**Issue by sircharleswatson** [frozeman/meteor-build-client#14]
I'm trying to use this tool on a newly created app and when I open the index.html in the browser, Meteor is never defined and hence doesn't run the app at all.

I had to edit the index.html to have a `.` in front of the css href link and the script src files.

Even then, I'm still getting errors:

```
XMLHttpRequest cannot load file:///sockjs/info?cb=sh1vwpyq6g. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.w._start @ b3f39905266a5d98e7a045660ed3ec524ed47482.js:32(anonymous function) @ b3f39905266a5d98e7a045660ed3ec524ed47482.js:32

Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///sockjs/info?cb=sh1vwpyq6g'.w._start @ b3f39905266a5d98e7a045660ed3ec524ed47482.js:32(anonymous function) @ b3f39905266a5d98e7a045660ed3ec524ed47482.js:32
```

**Comment by GeoffreyBooth** [comment]
Are you loading the generated `index.html` via `file://`? [That probably won't work](http://stackoverflow.com/a/5469527/223225). It needs to start with `http` or `https`.

Make sure the site is loaded via a webserver, for example Apache; if you’re on Mac, I recommend [these instructions](https://echo.co/blog/os-x-1010-yosemite-local-development-environment-apache-php-and-mysql-homebrew).

**Comment by GarethWright** [comment]
Node is great for firing up a quick webserver.

`npm install http-server -g` 

`cd <your app route>`

`http-server --cors`

**Comment by frozeman** [comment]
@sircharleswatson did this actually solve your problem?

Starting with file protocol should actually work if you build it using `$ meteor-build-client ../build --path ""`

**Comment by gnorbsl** [comment]
In case anyone stumbles over this issue like me, I forgot to run `npm install` in the app folder before building it. After that everything worked and Meteor was defined.

**Comment by dr-dimitru** [comment]
This issue is archived.
Feel free to reopen it in case if the issue is still persists on your end.
