### ISSUE TITLE
EPERM issue in Windows 8.1

### ISSUE THREAD

**Issue by Type1J** [frozeman/meteor-build-client#16]
```
Generating the index.html...

fs.js:760
  return binding.unlink(pathModule._makeLong(path));
                 ^
Error: EPERM, operation not permitted 'c:\Users\user\Projects\testMeteor\test_client\bundle\main.js'
    at Object.fs.unlinkSync (fs.js:760:18)
    at c:\Users\user\AppData\Roaming\npm\node_modules\meteor-build-client\meteor.js:45:20
    at Array.forEach (native)
    at deleteFolderRecursive (c:\Users\user\AppData\Roaming\npm\node_modules\meteor-build-client\meteor.js:40:15)
    at Object.module.exports.cleanUp (c:\Users\user\AppData\Roaming\npm\node_modules\meteor-build-client\meteor.js:165:9)
    at c:\Users\user\AppData\Roaming\npm\node_modules\meteor-build-client\main.js:84:20
    at null._onTimeout (c:\Users\user\AppData\Roaming\npm\node_modules\meteor-build-client\queue.js:41:11)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

It looks like it's trying to delete a file that was created during the build. I don't know why permissions were set such that it couldn't delete it. I'm on a Windows 8.1 box, and I ran it under MSYS bash, if that helps.

_test_ was my project directory and _test_client_ was in the same directory as _test_, and it was my build directory.

**Comment by Type1J** [comment]
Here's a confirmation that it creates files as 444:

    $ ls -l
    total 2
    -r--r--r--    1 user Administ      543 Sep 11 09:13 README
    -r--r--r--    1 user Administ      485 Sep 11 09:13 main.js
    drwxr-xr-x    4 user Administ        0 Sep 11 09:13 programs/
    drwxr-xr-x    3 user Administ        0 Sep 11 09:13 server/
    -r--r--r--    1 user Administ      392 Sep 11 09:13 star.json
    
    user@MACHINE ~/Projects/testMeteor/test_client/bundle
    $ rm main.js
    rm: remove write-protected file `main.js'?
This was using MSYS bash on a Windows 8.1 machine. I'm guessing that since the user still owns the files, then if EPERM is detected, a permission change could be requested.

**Comment by GarethWright** [comment]
Similar behavior on Windows 7, even when running in CMD (as Admin)
`
Error: EPERM, operation not permitted 'C:\Users\garethw\Desktop\Tidy\rmsClient\5
bfc97ade90aff3c0e92c06cc55823f48b82e302.css'
    at Object.fs.unlinkSync (fs.js:772:18)
    at Object.module.exports.addIndexFile (C:\Users\garethw\AppData\Roaming\npm\
node_modules\meteor-build-client\meteor.js:118:16)
    at C:\Users\garethw\AppData\Roaming\npm\node_modules\meteor-build-client\mai
n.js:79:20
    at null._onTimeout (C:\Users\garethw\AppData\Roaming\npm\node_modules\meteor
-build-client\queue.js:41:11)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
`

**Comment by Type1J** [comment]
Sorry, I would have tested and made a pull request, but I have other machines that aren't running Windows on which "meteor-build-client" works correctly, and I haven't gotten around to trying to fix it on Windows, but here's what I was planning:

I haven't tried it, but it may be fine if the umask was set temporarily when the files are created:

    var oldmask = process.umask(newmask);
    fs.open(path, flags, [mode], callback)
    process.umask(oldmask);

I got the example code from [here](http://www.z-car.com/blog/programming/node-js-fs-openfs-writefile-mode-file-permissions-umask-and-how-they-interact) where they had a similar problem, but that's assuming that "meteor-build-client" has control over the creation. If not, then umask could be set for the entire build, and then set back afterward.

**Comment by frozeman** [comment]
If somebody can test this would be great.

**Comment by dr-dimitru** [comment]
This issue is archived.
Feel free to reopen it in case if the issue is still persists on your end.
