### ISSUE TITLE
Bundled JS and CSS 404 Errors

### ISSUE THREAD

**Issue by GarethWright** [frozeman/meteor-build-client#17]
Noticed these today on Windows and after hours pulling out my hair it seems it's a simple file name too long error.

Renaming to 1.js and 1.css fixed the issue

**Comment by frozeman** [comment]
I dont understand why long file names would be a problem on windows.

**Comment by lukeadams** [comment]
https://msdn.microsoft.com/en-us/library/aa365247.aspx#maxpath
Not sure if this is it, but they suggest using < 260 characters.

@GarethWright What version of windows are you using?

**Comment by GarethWright** [comment]
7 Pro

**Comment by dr-dimitru** [comment]
This issue is archived.
Feel free to reopen it in case if the issue is still persists on your end.
