### ISSUE TITLE
star.json not found

### ISSUE THREAD

**Issue by lukeadams** [frozeman/meteor-build-client#19]
Here:
```js
Bundling Meteor app...
Generating the index.html...
module.js:338
    throw err;
    ^

Error: Cannot find module '/Users/lukeadams/Projects/belljar-io/Users/lukeadams/Desktop/buildtest/bundle/star.json'
```
It has to do with relative URL handling
PR incoming...

**Comment by lukeadams** [comment]
#20 fixes it for my use case (`meteor-build-client ~/<mypath>`)
Didn't really test more than that

**Comment by frozeman** [comment]
Thanks for the fix. I assume path like `../build` still works.

**Comment by lukeadams** [comment]
Yup! Just tested it.

**Comment by frozeman** [comment]
Ok i released a new version with your PR included
