### ISSUE TITLE
Command failed: /bin/sh -c meteor build

### ISSUE THREAD

**Issue by hakimelek** [frozeman/meteor-build-client#22]
I have run the command `meteor-build-client ../build -p ''` on a meteor project folder. 
I keep getting the same issue 

```
Bundling Meteor app...
Command failed: /bin/sh -c meteor build ../build --directory
Supply the server hostname and port in the --server option for mobile app
builds.

 undefined
```

Any help? 
Thanks.

**Comment by loicginoux** [comment]
You will have to pass a -u argument to the command that will add a `--server` to the command.

```meteor-build-client -h```

```meteor-build-client ../myOutputFolder -u localhost:3000```

**Comment by frozeman** [comment]
i probably should change the flag :P

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
