### ISSUE TITLE
SockJs errors

### ISSUE THREAD

**Issue by ColonelBundy** [frozeman/meteor-build-client#24]
```
XMLHttpRequest cannot load file:///sockjs/info?cb=xg7uuxnabr. 
Cross origin requests are only supported for protocol schemes: 
http, data, chrome, chrome-extension, https, chrome-extension-resource.
```

Looked through the source and did some diagnosing and it seems like the `--server` flag is not working?

And the solution provided `DDPConnection = (Meteor.isClient) ? DDP.connect("http://localhost:3000/") : {};`

Did not work for me and it seems like a _dirty_ fix.

**Comment by frozeman** [comment]
If you have `<base href="/">` then this will redirect your requests and even the one for the socket, which might be the issue here.

The server flag is actually called `--url`

**Comment by makkesk8** [comment]
I'm already using --url and its not really working, even modifying the module it self to set:
```settings.ROOT_URL = "domain.com";``` and ```command += ' --server '+ "domain.com";``` doesn't work either.

Could it be a meteor issue?

**Comment by frozeman** [comment]
I comment this out, could you try on a local copy if that would fix it?
https://github.com/frozeman/meteor-build-client/blob/master/meteor.js#L150

**Comment by makkesk8** [comment]
Already tried that at the same time I tried the other modifications and even that didn't change the sockjs url

**Comment by frozeman** [comment]
I currently don't have the time, if you can figure it out please let me know!

**Comment by praneybehl** [comment]
I'm getting the same issue, was someone able to figure this?

**Comment by rickmed** [comment]
I'm too getting errors like 

GET file:///sockjs/info?cb=yy1u8c3uxh net::ERR_FILE_NOT_FOUND

meteor 1.3.2

**Comment by rickmed** [comment]
@frozeman the only way I was able to make it work (tried meteor 1.3.2.4 and 1.3.1) was to set the __meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL (which got rid of the sockjs issues) but now the autoupdate package indefinitely reloads the script so I had to get rid of it.

**Comment by bastiW** [comment]
@rickmed 

how did you set the ddp default connection url?

```

Meteor.startup(() => {
    __meteor_runtime_config__.DDP_DEFAULT_CONNECTION_URL="http://localhost:3000/"

});



```


Did you already solve the issue?

**Comment by bastiW** [comment]
Did anyone solve that alerady?

**Comment by loicginoux** [comment]
same error here :(

**Comment by frozeman** [comment]
Yeah the reloading is an issue i experienced myself. Im not sure how i solved it back then, tho.
Most of the apps i build don't connect to the meteor backend. 

If somebody has a viable solution, im happy to integrate it

**Comment by loicginoux** [comment]
related to #18 but solutions given their seem to not work either

**Comment by promentol** [comment]
March 2018, does anybody figured out a solution for this?
If someone knows a solution, please let us know, too critical for me now.

**Comment by dr-dimitru** [comment]
Closing in favor of [`v1.0.0`](https://github.com/frozeman/meteor-build-client/releases/tag/1.0.0), see this commit — https://github.com/frozeman/meteor-build-client/pull/62/commits/46c5538159304923af08a2845e39abc1f4e303ed
Feel free to reopen issue is not solved in v1

**Comment by andresavic** [comment]
@dr-dimitru I don't think this commit address the problem what this is about.

I have the same problem with the latest meteor version that my build can't connect to the server:
GET file:///sockjs/info?cb=0_8u67cd4y net::ERR_FILE_NOT_FOUND

I am using the --url parameter in the build process and also the ROOT_URL get correctly set in` __meteor_runtime_config__ = JSON.parse(decodeURIComponent(`

Does anyone know a solution? I am trying to build a PWA with Meteor and CapacitorJs.

**Comment by frozeman** [comment]
Try to call Meteor.disconnect() early in your code.

Kind regards,
Fabian

**Comment by andresavic** [comment]
@frozeman Thank you for your answer. But can you explain to me why disconnecting should solve my problem? 
I would like to connect to the server and not disconnect from them, just to suppress the error message. 
Best,
Andre
