### ISSUE TITLE
Getting errors with Meteor 1.3.1

### ISSUE THREAD

**Issue by arashsa** [frozeman/meteor-build-client#28]
I am getting errors with Meteor 1.3.1

I followed the instructions and get the index.html and js file. However, I get an error when I try to open the index.html file in Chrome.

Failed to load resource: net::ERR_FILE_NOT_FOUND
Uncaught TypeError: Cannot read property 'NODE_ENV' of undefined
Uncaught ReferenceError: Meteor is not defined

**Comment by mrzafod** [comment]
@arashsa, got the same. No issue for the momment?

**Comment by frozeman** [comment]
Can you please test this PR: https://github.com/frozeman/meteor-build-client/pull/27

**Comment by mrzafod** [comment]
@frozeman #27 works fine and it fixes startup errors. But we still can't run from ```file://``` to be shure that everything is ok. Don't you think it is possible to wrap builded static sources into simple node/express server for test? Just a thought

**Comment by mrzafod** [comment]
I've just wrap ```build``` folder with express/static server. So #27 works perfect, guess you can merge @frozeman

**Comment by dr-dimitru** [comment]
@mrzafod @arashsa hello from 2020. 
We got major codebase update and compatibility with latest Meteor and all of its features.
If you still "into Meteor" — give it a try. It should work well 

Closing due to silence.
Feel free to reopen it in case if the issue still persists on your end.
