### ISSUE TITLE
Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by Lauricio** [frozeman/meteor-build-client#3]
Hi,
Getting an error when trying to bundle sample meteor app, here are steps to reproduce it:
**I'am on MacOS 10.10.3 , Node v0.10.36, Meteor 1.1.0.2**

![screen shot 2015-05-02 at 4 17 18 pm](https://cloud.githubusercontent.com/assets/2200004/7440548/c5257e4c-f0e6-11e4-875a-eef20c870a85.png)

```
meteor create test-website
test-website: created.

To run your new app:
  cd test-website
  meteor
 ~/Projects 
» cd test-website
 ~/Projects/test-website 
» meteor-build-client ../myOutputFolder
Bundling app with Meteor...
Extracting the bundle...
|
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: ENOENT, lstat '/Users/su/Projects/myOutputFolder/app.tar.gz'
```

**Comment by Lauricio** [comment]
Tried upgrading node to version `v0.12.2`, but getting the same results.

**Comment by Lauricio** [comment]
It seems that the problem is in `unpack` method in:
```
    unpack: function(callback){
        var targz = require('tar.gz');

        spinner.start();
        new targz().extract(buildPath +'/app.tar.gz', buildPath, function(err){
            spinner.stop();

            if(err)
                console.log(err);

            callback();
        });
    },
```
 it expects `app.tar.gz` but the file outputted from `meteor build` is actually using **project root folder name** instead of `app`, in my case it was ``test-website.tar.gz`` so it  crashed due to not being apple to find it. Modifying the code to use  **project root folder name** instead of `app` fixes the issue for me, but would this break compatibility with previous meteor versions or other platforms? I can submit a PR if you think its a good solution

Thank you.

**Comment by frozeman** [comment]
ah so it takes the meteor folder as a zip name. haha
as i alwaysput the meteor project into an `app` folder into my project folder, i always got that file name.
i though it was universal.

would be nice if you could provide a PR, but essentially we only need to choose the `*.tar.gz` file.
its an easy fix

**Comment by frozeman** [comment]
Fixed it myself, Thanks for figuring it out!

**Comment by Lauricio** [comment]
Thank you for fast response and excellent tool, works great now!
