### ISSUE TITLE
React Support?

### ISSUE THREAD

**Issue by zeroasterisk** [frozeman/meteor-build-client#32]
Would this work for React meteor packages?

**Comment by vyky** [comment]
@zeroasterisk have you tested with React?

**Comment by praneybehl** [comment]
I guess why not. Did you give it a try? What errors are you getting?

**Comment by claudiut** [comment]
I tried this with React but nothing gets injected into the root container. Any ideas why?

**Comment by dr-dimitru** [comment]
Closed as seemed to be solved
Feel free to reopen it in case if the issue still persists on your end.
