### ISSUE TITLE
Using your package to build my meteor client application but is any way to give meteor server URL at runtime?

### ISSUE THREAD

**Issue by AnjaniKumar15** [frozeman/meteor-build-client#38]
Actually I am using your package to build my meteor client application. if I had provided meteor server URL at build time then it works fine, but I want to give meteor server URL at run time dynamically (ex. environment variable) then Is any way to do this thing? 
Its required because we have two Meteor admin servers and I want, when I change URL path of my client app hosted server environment variable, My meteor Client app redirect and connect with other server.

**Comment by dr-dimitru** [comment]
@AnjaniKumar15 I know it's been a while since you posted your question.
Have you solved it?
I can't answer it unless I see full picture — are those two servers meant for balancing?

**Comment by dr-dimitru** [comment]
Duplicate: #37
