### ISSUE TITLE
Build on win10, question

### ISSUE THREAD

**Issue by Isotheos** [frozeman/meteor-build-client#43]
In the command prompt not available meteor-build-client command
Maybe it's not installed, becouse no `meteor_build_client` catalog in `node_modules` directory on root of project.
can you help me?
sorry for my english

**Comment by dr-dimitru** [comment]
Closing in favor of [`v1.0.0`](https://github.com/frozeman/meteor-build-client/releases/tag/1.0.0). Please, follow updated docs.
Feel free to reopen issue is not solved in v1
