### ISSUE TITLE
Getting unusable builds

### ISSUE THREAD

**Issue by izqui** [frozeman/meteor-build-client#44]
I'm having trouble compiling using the tool.

Both `meteor-build-client ../build -p ""`  and `meteor-build-client ../build2 -u http://localhost:8080` result in this HTML file which tries to load `/undefined`:

```html

<html>
    <head>
        <link rel="stylesheet" type="text/css" class="__meteor-css__" href="/a9c351b0b865337742fa34ec4882eb46352b3755.css?meteor_css_resource=true">
        <script type="text/javascript">__meteor_runtime_config__ = JSON.parse(decodeURIComponent("%7B%22meteorRelease%22%3A%22METEOR%401.4.2.3%22%2C%22ROOT_URL_PATH_PREFIX%22%3A%22%22%2C%22meteorEnv%22%3A%7B%22NODE_ENV%22%3A%22production%22%7D%2C%22ROOT_URL%22%3A%22http%3A%2F%2Flocalhost%3A8080%22%7D"));</script>
        <script type="text/javascript" src="/undefined"></script>

        <meta charset="utf-8">
    <title>Project name</title>
    </head>
    <body>
    </body>
</html>
```

When changing index.html `/undefined` for `/app.js` I'm getting `Uncaught ReferenceError: meteorInstall is not defined at app.js:1`.

Am i missing something? 

Thanks

**Comment by dr-dimitru** [comment]
Closing in favor of [`v1.0.0`](https://github.com/frozeman/meteor-build-client/releases/tag/1.0.0).
Feel free to reopen issue is not solved in v1
