### ISSUE TITLE
"Clear" file.js ?

### ISSUE THREAD

**Issue by BritishBulldog** [frozeman/meteor-build-client#50]
Hi all, just a newbie question: 
I'm trying 
>meteor-build-client ../dappfolder -p ""
getting four files:
_a04db942e7de2b04c9b00de5bef17125c78658bb.css
index.html
e172b96067632038a7553b637811428b18c5c483.js
e172b96067632038a7553b637811428b18c5c483.stats.json_

I can't get the "clear code" of _e172b96067632038a7553b637811428b18c5c483.js_ , but something like:

_!function(){var t,e,n;(function(){t=this}).call(this),function(){e=__meteor_runtime_config__.meteorEnv, ...
"undefined"==typeof Package&&(Package={}),Package["meteor-base"]={}; ..._

How can I get the code of e172b96067632038a7553b637811428b18c5c483.js for a standalone, verifiable serverless application?

Thank you so much for your time and sorry for my poor english

**Comment by dr-dimitru** [comment]
@BritishBulldog what do you mean by 

> "clear code" of e172b96067632038a7553b637811428b18c5c483.js

??

You're getting compiled (*bundled*) app, and code is minified.

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
