### ISSUE TITLE
Is this project dead? Are you looking for new owners?

### ISSUE THREAD

**Issue by dr-dimitru** [frozeman/meteor-build-client#51]
If you do, we will be happy to continue your work.
@frozeman please, do not stay quiet.

**Comment by dr-dimitru** [comment]
//cc @mksh-su

**Comment by jankapunkt** [comment]
Some status update on this @frozeman ?

@dr-dimitru are you willing to fork and continue if the maintainer does not respond? With Meteor > 1.7 there may be even more things that require active maintenance.

**Comment by dr-dimitru** [comment]
@jankapunkt thank fot the interest.
We will use this lib for one of the our ongoing projects later this month.
So, we will have to fork it and adapt for 1.7.*
Stay tuned :)

@frozeman if you're ready to give us access to rep/npm - this will save lib's life.
If not, we will just go with a fork :)

**Comment by frozeman** [comment]
yes please continue the work. I can add you as a maintainer and to npm
On 18.

**Comment by frozeman** [comment]
I send an invite for the repo @dr-dimitru what’s your mom name?

**Comment by dr-dimitru** [comment]
Hello @frozeman m

Thank you for stepping forward, my NPM name is [`dr.dimitru`](https://www.npmjs.com/~dr.dimitru)
We're planning to start development on the next week.

**Comment by frozeman** [comment]
i added you, as well as to this repo
