### ISSUE TITLE
Does it work with meteor 1.8?

### ISSUE THREAD

**Issue by hamzamu** [frozeman/meteor-build-client#57]
Hello,
Does Meteor-build-client work with the latest release of Meteor?  I have used it successfully with Meteor 1.6 but not with Meteor 1.8.

**Comment by harryli0088** [comment]
I've successfully used this package on Meteor 1.8.1 and React 16.5.0!

**Comment by dr-dimitru** [comment]
Hello @hamzamu  ,

Thank you for asking, — just published [`v1.0.0`](https://github.com/frozeman/meteor-build-client/releases/tag/1.0.0) tested and compatible with recent meteor release and its ecosystem packages. Please, give it a try and let me know if there's any issues.

**Comment by hamzamu** [comment]
It works with 1.8 very fine thank you.
But not : Meteor 1.11.1 or 1.11

**Comment by dr-dimitru** [comment]
Thank you for reporting this @hamzamu 
Please, open the new issue. Meanwhile I'll run tests

**Comment by dr-dimitru** [comment]
Hello @hamzamu ,

Did you still have an issue building on `meteor@1.11.*` ?

If so, please, tell me more details and join us in #63

**Comment by hamzamu** [comment]
@dr-dimitru  sure, I will run some tests today.
