### ISSUE TITLE
Does not work with blaze

### ISSUE THREAD

**Issue by brucejo75** [frozeman/meteor-build-client#64]
1. Blaze does not output a `body.html` file into the build.
2. Adding the tag `<meteor-bundled-js />` to the body of a blaze app will fail on compile:
```
=> Errors prevented startup:

   While processing files with templating-compiler (for target web.browser):
   client/main.html:14: Only certain elements like BR, HR, IMG, etc. (and foreign elements like SVG) are allowed to
   self-close
   ...<meteor-bundled-js />   <h1>Welcome to Me...
   ^
```

As a consequence, there is no way to add the scripts files for meteor projects.

**Comment by brucejo75** [comment]
#65 fixes this.  Will close when it is merged and released.

**Comment by dr-dimitru** [comment]
@brucejo75 please update to the latest release this issue should be solved.
let me know

**Comment by technicalbirdVayuz** [comment]
Hi,

Checked the doc, <meteor-bundled-js />  should not be added when the project is created in Blaze, I was making the same mistake, @dr-dimitru  Please share your input on this


Also, one thing I would like to mention is that if dynamic imports are being used then the package is not working as expected

**Comment by brucejo75** [comment]
@technicalbirdVayuz, have not looked at this for a while...

Check the solution in #63, code change is [here](https://github.com/frozeman/meteor-build-client/pull/65/files), documented in comments.  Solution does not add a `<body>` tag so Blaze can do its thing.

**Comment by dr-dimitru** [comment]
@brucejo75 @technicalbirdVayuz was it solved for you? Or we still need to update/change something? in the docs?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
