### ISSUE TITLE
Does it support meteor/server-render server side render?

### ISSUE THREAD

**Issue by imhazige** [frozeman/meteor-build-client#68]
For SSR:
https://docs.meteor.com/packages/server-render.html#Streaming-HTML

we have some dynamic data need insert in the onPageLoad, I have tried, but it did not work with the static file, is there a solution?

**Comment by dr-dimitru** [comment]
@imhazige only theoretically, if you can hook into middleware pipeline. So far this package was focused on building a tool to serve front-end as a single file (which can later connect to a server if needed)
