### ISSUE TITLE
Is autoreload possible on code change in Electron?

### ISSUE THREAD

**Issue by wildfiremedia** [frozeman/meteor-build-client#7]
On Windows, does it uses all the same feature in this meteor build client including the ability to reload page when it detect code change?

**Comment by frozeman** [comment]
Once you build the client, you loose all the auto reload functionality, as the files revered are static and not from a meteor server.

**Comment by dr-dimitru** [comment]
This issue is archived.
Feel free to reopen it in case if the issue is still persists on your end.
