### ISSUE TITLE
css is not included in the generated index.html

### ISSUE THREAD

**Issue by moky80** [frozeman/meteor-build-client#72]
**How to reproduce the issue**
meteor@release-2.9
meteor-build-client@1.3.0

Create blaze app: `$ meteor create --blaze my-blaze-app`
Build client: `my-blaze-app$ meteor-build-client ../my-blaze-app-client-bundle`

The generated client bundle contained a bundled css (c47dbe2a38954933b4ffc1fe3cf58f51146830bd.css) but did not include it in the generated index.html

**How to fix the issue manually**
Manually inserted `<link rel="stylesheet" type="text/css" href="c47dbe2a38954933b4ffc1fe3cf58f51146830bd.css">` into index.html worked

**Expected fix**
I would expect the css be automatically included in the index.html by meteor-build-client.
I would also like to do a PR (because meteor-build-client is needed for our project) if some hints are given as where to start with.

**Comment by dr-dimitru** [comment]
@minnie80 hello

Will it get solved with `<meteor-bundled-css />`?

```html
<head>
  <!-- your header stuff... -->
  <!-- then typically add the css link at the bottom of the head -->
  <meteor-bundled-css />
</head>
```

**Comment by moky80** [comment]
Yes, it works. Thanks a lot.

**Comment by dr-dimitru** [comment]
@minnie80 I'm glad this was quickly solved, sorry for this, but small non-breaking changes are required to use this package

**Comment by moky80** [comment]
Would be nice if meteor-build-client could automate this. Maybe I am just not aware of the constraints that make it difficult / impossible? But overall am already very happy with the "non-breaking changes" that is required to be added to my html. I also very appreciate that the information was actually already available in the README.
