### ISSUE TITLE
Relative path support on windows 7. Bug 

### ISSUE THREAD

**Issue by iSuslov** [frozeman/meteor-build-client#8]
Can not set empty path to make it relative. OS Windows 7 x64
![](http://pix.academ.org/img/2015/06/29/7113c544a1d29893280c50aadcfcc0a5.png)

**Comment by frozeman** [comment]
This seems to be an issue with the `commander` module. Could you create an issue there please?
https://github.com/tj/commander.js

**Comment by frozeman** [comment]
And can you try using `--path " "`

**Comment by dr-dimitru** [comment]
This issue is archived.
Feel free to reopen it in case if the issue is still persists on your end.
